In [ ]:
import pandas as pd
import os
import ast
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Memuat Dataset

In [ ]:
# Membaca CSV dari link download langsung
resep_df = pd.read_csv('https://drive.google.com/uc?export=download&id=1YMqtxOs2hBLxcQ3-husLieTHAYoJy-ph')

resep_df.head()

/tmp/ipykernel_17954/4052929907.py:2: DtypeWarning: Columns (1,2,4,5,6,7,8,9,10,11,12,13,14,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  resep_df = pd.read_csv('https://drive.google.com/uc?export=download&id=1YMqtxOs2hBLxcQ3-husLieTHAYoJy-ph')

,RecipeId,Barcode,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38.0,*38*,Low-Fat Berry Blue Frozen Dessert,1533.0,Dancer,PT24H,PT45M,PT24H45M,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,...,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,39.0,*39*,Biryani,1567.0,elly9812,PT25M,PT4H,PT4H25M,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,...,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,40.0,*40*,Best Lemonade,1566.0,Stephen Little,PT5M,PT30M,PT35M,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,...,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."
3,41.0,*41*,Carina's Tofu-Vegetable Kebabs,1586.0,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03T14:54:00Z,This dish is best prepared a day in advance to...,...,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc..."
4,42.0,*42*,Cabbage Soup,1538.0,Duckie067,PT30M,PT20M,PT50M,1999-09-19T06:19:00Z,Make and share this Cabbage Soup recipe from F...,...,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"c(""Mix everything together and bring to a boil..."

In [ ]:
#melihat tipe data kolom
resep_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048543 entries, 0 to 1048542
Data columns (total 29 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   RecipeId                    1228 non-null    float64
 1   Barcode                     527203 non-null  object
 2   Name                        1228 non-null    object
 3   AuthorId                    1228 non-null    float64
 4   AuthorName                  1228 non-null    object
 5   CookTime                    725 non-null     object
 6   PrepTime                    1228 non-null    object
 7   TotalTime                   1228 non-null    object
 8   DatePublished               1228 non-null    object
 9   Description                 1228 non-null    object
 10  Images                      1228 non-null    object
 11  RecipeCategory              1228 non-null    object
 12  Keywords                    1215 non-null    object
 13  RecipeIngredientQuantities  1227 non-null    object
 14  RecipeIngredientParts       1228 non-null    object
 15  AggregatedRating            983 non-null     float64
 16  ReviewCount                 996 non-null     float64
 17  Calories                    1228 non-null    float64
 18  FatContent                  1228 non-null    float64
 19  SaturatedFatContent         1228 non-null    float64
 20  CholesterolContent          1228 non-null    float64
 21  SodiumContent               1228 non-null    float64
 22  CarbohydrateContent         1228 non-null    float64
 23  FiberContent                1228 non-null    float64
 24  SugarContent                1228 non-null    float64
 25  ProteinContent              1228 non-null    float64
 26  RecipeServings              823 non-null     float64
 27  RecipeYield                 389 non-null     object
 28  RecipeInstructions          1228 non-null    object
dtypes: float64(14), object(15)
memory usage: 232.0+ MB

In [ ]:
#melihat informasi statistika umum
resep_df.describe()

,RecipeId,AuthorId,AggregatedRating,ReviewCount,Calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings
count,1228.000000,1228.000000,983.000000,996.000000,1228.000000,1228.000000,1228.000000,1228.000000,1228.000000,1228.000000,1228.000000,1228.000000,1228.000000,823.000000
mean,1073.337948,13418.272801,4.480671,10.822289,666.207329,32.847476,13.008876,107.790554,781.737296,75.664821,4.703664,38.437215,18.487866,7.989064
std,841.259236,37838.010652,0.737512,34.476932,1034.320856,62.188265,26.787176,216.356217,1485.511028,142.507875,8.435878,103.652955,28.262034,10.588229
min,38.000000,1530.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,371.750000,1539.000000,4.000000,2.000000,180.525000,5.200000,1.500000,4.750000,126.350000,14.200000,0.800000,2.800000,3.075000,4.000000
50%,717.000000,1559.000000,5.000000,3.000000,331.650000,14.200000,5.000000,46.400000,332.200000,32.850000,2.000000,8.700000,7.950000,6.000000
75%,1750.750000,1727.000000,5.000000,8.000000,648.675000,31.325000,12.700000,115.525000,815.675000,63.350000,4.600000,28.625000,23.800000,8.000000
max,2664.000000,451242.000000,5.000000,609.000000,7798.200000,689.300000,290.500000,2366.800000,16129.000000,1579.000000,96.200000,1092.100000,308.200000,192.000000

In [ ]:
#mengecek missing values
missing_table = pd.DataFrame({
    'missing_count': resep_df.isnull().sum(),
    'missing_percentage': resep_df.isnull().sum() / len(resep_df) * 100
})

missing_table = missing_table[missing_table['missing_count'] > 0]
missing_table.sort_values(by='missing_count', ascending=False)

                            missing_count  missing_percentage
RecipeYield                       1048154           99.962901
CookTime                          1047818           99.930856
RecipeServings                    1047720           99.921510
AggregatedRating                  1047560           99.906251
ReviewCount                       1047547           99.905011
Keywords                          1047328           99.884125
RecipeIngredientQuantities        1047316           99.882980
TotalTime                         1047315           99.882885
AuthorName                        1047315           99.882885
DatePublished                     1047315           99.882885
AuthorId                          1047315           99.882885
Name                              1047315           99.882885
RecipeId                          1047315           99.882885
CholesterolContent                1047315           99.882885
RecipeCategory                    1047315           99.882885
Description                       1047315           99.882885
Images                            1047315           99.882885
PrepTime                          1047315           99.882885
FatContent                        1047315           99.882885
Calories                          1047315           99.882885
RecipeIngredientParts             1047315           99.882885
SugarContent                      1047315           99.882885
SaturatedFatContent               1047315           99.882885
SodiumContent                     1047315           99.882885
CarbohydrateContent               1047315           99.882885
ProteinContent                    1047315           99.882885
FiberContent                      1047315           99.882885
RecipeInstructions                1047315           99.882885
Barcode                            521340           49.720422

In [ ]:
#memilih kolom yang relevan untuk proyek serta melakukan drop pada kolom yang banyak missing values

selected_cols = [
    'RecipeId',
    'Name',
    'RecipeIngredientParts',
    'RecipeInstructions',
    'Images'
]

df_clean = resep_df[selected_cols].copy()

df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"c(""blueberries"", ""granulated sugar"", ""vanilla ...","c(""Toss 2 cups berries with sugar."", ""Let stan...","c(""https://img.sndimg.com/food/image/upload/w_..."
1,39.0,Biryani,"c(""saffron"", ""milk"", ""hot green chili peppers""...","c(""Soak saffron in warm milk for 5 minutes and...","c(""https://img.sndimg.com/food/image/upload/w_..."
2,40.0,Best Lemonade,"c(""sugar"", ""lemons, rind of"", ""lemon, zest of""...","c(""Into a 1 quart Jar with tight fitting lid, ...","c(""https://img.sndimg.com/food/image/upload/w_..."
3,41.0,Carina's Tofu-Vegetable Kebabs,"c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...","c(""Drain the tofu, carefully squeezing out exc...","c(""https://img.sndimg.com/food/image/upload/w_..."
4,42.0,Cabbage Soup,"c(""plain tomato juice"", ""cabbage"", ""onion"", ""c...","c(""Mix everything together and bring to a boil...","""https://img.sndimg.com/food/image/upload/w_55..."

In [ ]:
#mengecek missing values setelah dilakukan seleksi kolom yang relevan

df_clean.isnull().sum()

RecipeId                 1047315
Name                     1047315
RecipeIngredientParts    1047315
RecipeInstructions       1047315
Images                   1047315
dtype: int64

In [ ]:
# melakukan drop pada missing values setelah melakukan seleksi kolom
df_clean = df_clean.dropna()

df_clean.isnull().sum()

RecipeId                 0
Name                     0
RecipeIngredientParts    0
RecipeInstructions       0
Images                   0
dtype: int64

In [ ]:
# melakukan cek pada
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
#hapus data duplikasi (jaga-jaga jika ada)
df_clean.drop_duplicates(inplace=True)
print("Jumlah duplikasi data:" , df_clean.duplicated().sum())

Jumlah duplikasi data: 0

In [ ]:
df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"c(""blueberries"", ""granulated sugar"", ""vanilla ...","c(""Toss 2 cups berries with sugar."", ""Let stan...","c(""https://img.sndimg.com/food/image/upload/w_..."
1,39.0,Biryani,"c(""saffron"", ""milk"", ""hot green chili peppers""...","c(""Soak saffron in warm milk for 5 minutes and...","c(""https://img.sndimg.com/food/image/upload/w_..."
2,40.0,Best Lemonade,"c(""sugar"", ""lemons, rind of"", ""lemon, zest of""...","c(""Into a 1 quart Jar with tight fitting lid, ...","c(""https://img.sndimg.com/food/image/upload/w_..."
3,41.0,Carina's Tofu-Vegetable Kebabs,"c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...","c(""Drain the tofu, carefully squeezing out exc...","c(""https://img.sndimg.com/food/image/upload/w_..."
4,42.0,Cabbage Soup,"c(""plain tomato juice"", ""cabbage"", ""onion"", ""c...","c(""Mix everything together and bring to a boil...","""https://img.sndimg.com/food/image/upload/w_55..."

In [ ]:
# 3. Fungsi untuk membersihkan format c("bahan1", "bahan2") menjadi list Python seutuhnya
def bersihkan_bahan(teks_bahan):
    try:
        # Menghapus pola c() bawaan dari CSV
        teks_bersih = re.sub(r'^c\((.*)\)$', r'[\1]', teks_bahan)
        # Mengubah string '["bahan1", "bahan2"]' menjadi list asli ['bahan1', 'bahan2']
        return ast.literal_eval(teks_bersih)
    except:
        return []

In [ ]:
df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"c(""blueberries"", ""granulated sugar"", ""vanilla ...","c(""Toss 2 cups berries with sugar."", ""Let stan...","c(""https://img.sndimg.com/food/image/upload/w_..."
1,39.0,Biryani,"c(""saffron"", ""milk"", ""hot green chili peppers""...","c(""Soak saffron in warm milk for 5 minutes and...","c(""https://img.sndimg.com/food/image/upload/w_..."
2,40.0,Best Lemonade,"c(""sugar"", ""lemons, rind of"", ""lemon, zest of""...","c(""Into a 1 quart Jar with tight fitting lid, ...","c(""https://img.sndimg.com/food/image/upload/w_..."
3,41.0,Carina's Tofu-Vegetable Kebabs,"c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...","c(""Drain the tofu, carefully squeezing out exc...","c(""https://img.sndimg.com/food/image/upload/w_..."
4,42.0,Cabbage Soup,"c(""plain tomato juice"", ""cabbage"", ""onion"", ""c...","c(""Mix everything together and bring to a boil...","""https://img.sndimg.com/food/image/upload/w_55..."

In [ ]:
# 1. Buat fungsi pembersih khusus format c("...", "...")
def bersihkan_format_r(teks):
    # Jika data kosong (NaN)
    if pd.isna(teks):
        return []

    # Jika data ternyata sudah berbentuk list murni
    if isinstance(teks, list):
        return teks

    # Jika data berbentuk string, lakukan pembersihan
    if isinstance(teks, str):
        teks = teks.strip()
        # Mendeteksi jika string diawali dengan 'c(' dan diakhiri ')'
        if teks.startswith("c(") and teks.endswith(")"):
            # Ubah c("bahan1", "bahan2") menjadi ["bahan1", "bahan2"]
            teks = "[" + teks[2:-1] + "]"

        try:
            # Ubah string teks tadi menjadi List Python sesungguhnya
            return ast.literal_eval(teks)
        except:
            return [] # Jika gagal parse, kembalikan list kosong

    return []

In [ ]:
df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"c(""blueberries"", ""granulated sugar"", ""vanilla ...","c(""Toss 2 cups berries with sugar."", ""Let stan...","c(""https://img.sndimg.com/food/image/upload/w_..."
1,39.0,Biryani,"c(""saffron"", ""milk"", ""hot green chili peppers""...","c(""Soak saffron in warm milk for 5 minutes and...","c(""https://img.sndimg.com/food/image/upload/w_..."
2,40.0,Best Lemonade,"c(""sugar"", ""lemons, rind of"", ""lemon, zest of""...","c(""Into a 1 quart Jar with tight fitting lid, ...","c(""https://img.sndimg.com/food/image/upload/w_..."
3,41.0,Carina's Tofu-Vegetable Kebabs,"c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...","c(""Drain the tofu, carefully squeezing out exc...","c(""https://img.sndimg.com/food/image/upload/w_..."
4,42.0,Cabbage Soup,"c(""plain tomato juice"", ""cabbage"", ""onion"", ""c...","c(""Mix everything together and bring to a boil...","""https://img.sndimg.com/food/image/upload/w_55..."

In [ ]:
# 1. Bikin fungsi pembersih baru berbasis REGEX
def bersihkan_bahan_regex(teks):
    if pd.isna(teks):
        return []

    if isinstance(teks, list):
        return teks

    if isinstance(teks, str):
        # Mengambil semua teks yang diapit oleh tanda kutip ganda "..." atau tunggal '...'
        # Cara ini 100% aman dari error malformed string
        ekstrak_bahan = re.findall(r'["\']([^"\']+)["\']', teks)

        # Ubah langsung ke huruf kecil semua (lowercase) agar seragam
        return [bahan.lower().strip() for bahan in ekstrak_bahan]

    return []

# 2. Terapkan fungsi baru ini ke dataset kamu
df_clean['RecipeIngredientParts'] = df_clean['RecipeIngredientParts'].apply(bersihkan_bahan_regex)

# 3. KITA CEK LANGSUNG HASILNYA
print("--- CEK HASIL PEMBERSIHAN ---")
print("Baris pertama sekarang berisi:")
print(df_clean['RecipeIngredientParts'].iloc[0])

--- CEK HASIL PEMBERSIHAN ---
Baris pertama sekarang berisi:
['blueberries', 'granulated sugar', 'vanilla yogurt', 'lemon juice']

In [ ]:
df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"[blueberries, granulated sugar, vanilla yogurt...","c(""Toss 2 cups berries with sugar."", ""Let stan...","c(""https://img.sndimg.com/food/image/upload/w_..."
1,39.0,Biryani,"[saffron, milk, hot green chili peppers, onion...","c(""Soak saffron in warm milk for 5 minutes and...","c(""https://img.sndimg.com/food/image/upload/w_..."
2,40.0,Best Lemonade,"[sugar, lemons, rind of, lemon, zest of, fresh...","c(""Into a 1 quart Jar with tight fitting lid, ...","c(""https://img.sndimg.com/food/image/upload/w_..."
3,41.0,Carina's Tofu-Vegetable Kebabs,"[extra firm tofu, eggplant, zucchini, mushroom...","c(""Drain the tofu, carefully squeezing out exc...","c(""https://img.sndimg.com/food/image/upload/w_..."
4,42.0,Cabbage Soup,"[plain tomato juice, cabbage, onion, carrots, ...","c(""Mix everything together and bring to a boil...","""https://img.sndimg.com/food/image/upload/w_55..."

In [ ]:
# 4. Hapus resep yang tidak punya bahan setelah dibersihkan
df_clean = df_clean[df_clean['RecipeIngredientParts'].map(len) > 0]

In [ ]:
df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"[blueberries, granulated sugar, vanilla yogurt...","c(""Toss 2 cups berries with sugar."", ""Let stan...","c(""https://img.sndimg.com/food/image/upload/w_..."
1,39.0,Biryani,"[saffron, milk, hot green chili peppers, onion...","c(""Soak saffron in warm milk for 5 minutes and...","c(""https://img.sndimg.com/food/image/upload/w_..."
2,40.0,Best Lemonade,"[sugar, lemons, rind of, lemon, zest of, fresh...","c(""Into a 1 quart Jar with tight fitting lid, ...","c(""https://img.sndimg.com/food/image/upload/w_..."
3,41.0,Carina's Tofu-Vegetable Kebabs,"[extra firm tofu, eggplant, zucchini, mushroom...","c(""Drain the tofu, carefully squeezing out exc...","c(""https://img.sndimg.com/food/image/upload/w_..."
4,42.0,Cabbage Soup,"[plain tomato juice, cabbage, onion, carrots, ...","c(""Mix everything together and bring to a boil...","""https://img.sndimg.com/food/image/upload/w_55..."

In [ ]:
# =====================================================================
# 1. FUNGSI PEMBERSIH KOLOM RecipeInstructions
# =====================================================================
def bersihkan_instruksi(teks):
    if pd.isna(teks):
        return ""
    if not isinstance(teks, str):
        return str(teks)

    # Ekstrak semua teks yang berada di dalam tanda kutip (langkah-langkah memasak)
    langkah_langkah = re.findall(r'["\']([^"\']+)["\']', teks)

    if not langkah_langkah:
        # Jika format aneh/bukan c(...), bersihkan karakter dasar saja
        teks_bersih = re.sub(r'^c\(|\)$', '', teks)
        return teks_bersih.replace('""', '"').strip()

    langkah_bersih = []
    for langkah in langkah_langkah:
        # A. Hilangkan enter tersembunyi (\n atau \r) dan tab (\t) di dalam teks langkah
        langkah = re.sub(r'[\r\n\t]+', ' ', langkah)
        # B. Hilangkan spasi ganda/aneh yang berlebihan menjadi satu spasi normal
        langkah = re.sub(r'\s+', ' ', langkah)
        langkah = langkah.strip()

        if langkah:
            langkah_bersih.append(langkah)

    # C. Gabungkan menjadi teks berurutan (1. ..., 2. ...) dipisahkan enter normal (\n)
    # Format ini otomatis dibaca sangat rapi oleh Streamlit markdown
    instruksi_final = "\n".join([f"{i+1}. {l}" for i, l in enumerate(langkah_bersih)])
    return instruksi_final

# Terapkan ke kolom instruksi
df_clean['RecipeInstructions'] = df_clean['RecipeInstructions'].apply(bersihkan_instruksi)

In [ ]:
df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"[blueberries, granulated sugar, vanilla yogurt...",1. Toss 2 cups berries with sugar.\n2. Let sta...,"c(""https://img.sndimg.com/food/image/upload/w_..."
1,39.0,Biryani,"[saffron, milk, hot green chili peppers, onion...",1. Soak saffron in warm milk for 5 minutes and...,"c(""https://img.sndimg.com/food/image/upload/w_..."
2,40.0,Best Lemonade,"[sugar, lemons, rind of, lemon, zest of, fresh...","1. Into a 1 quart Jar with tight fitting lid, ...","c(""https://img.sndimg.com/food/image/upload/w_..."
3,41.0,Carina's Tofu-Vegetable Kebabs,"[extra firm tofu, eggplant, zucchini, mushroom...","1. Drain the tofu, carefully squeezing out exc...","c(""https://img.sndimg.com/food/image/upload/w_..."
4,42.0,Cabbage Soup,"[plain tomato juice, cabbage, onion, carrots, ...",1. Mix everything together and bring to a boil...,"""https://img.sndimg.com/food/image/upload/w_55..."

In [ ]:
# =====================================================================
# 2. FUNGSI PEMBERSIH KOLOM Images (SUDAH DIPERBAIKI)
# =====================================================================
def ambil_satu_gambar(teks):
    if pd.isna(teks):
        return ""
    if not isinstance(teks, str):
        return ""

    # PERBAIKAN: Menghapus koma (,) dari list pengecualian Regex.
    # Sekarang diperbolehkan membaca koma agar parameter gambar (w_555,h_416) tidak terpotong.
    # Regex ini akan berhenti tepat saat menyentuh tanda kutip (" atau ') atau tanda kurung tutup ).
    urls = re.findall(r'https?://[^"\s\')]+', teks)

    if urls:
        # Ambil hanya elemen pertama (link gambar pertama dari baris tersebut)
        link_pertama = urls[0].strip()
        return link_pertama

    return "" # Kembalikan string kosong jika resep tidak punya gambar

# =====================================================================
# JALANKAN ULANG PADA DATASET KAMU
# =====================================================================
df_clean['Images'] = df_clean['Images'].apply(ambil_satu_gambar)

In [ ]:
df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"[blueberries, granulated sugar, vanilla yogurt...",1. Toss 2 cups berries with sugar.\n2. Let sta...,https://img.sndimg.com/food/image/upload/w_555...
1,39.0,Biryani,"[saffron, milk, hot green chili peppers, onion...",1. Soak saffron in warm milk for 5 minutes and...,https://img.sndimg.com/food/image/upload/w_555...
2,40.0,Best Lemonade,"[sugar, lemons, rind of, lemon, zest of, fresh...","1. Into a 1 quart Jar with tight fitting lid, ...",https://img.sndimg.com/food/image/upload/w_555...
3,41.0,Carina's Tofu-Vegetable Kebabs,"[extra firm tofu, eggplant, zucchini, mushroom...","1. Drain the tofu, carefully squeezing out exc...",https://img.sndimg.com/food/image/upload/w_555...
4,42.0,Cabbage Soup,"[plain tomato juice, cabbage, onion, carrots, ...",1. Mix everything together and bring to a boil...,https://img.sndimg.com/food/image/upload/w_555...

In [ ]:
print("--- PEMBERSIHAN BERHASIL! ---")
# Cek hasil 1 baris sampel untuk pembuktian
print("\nHasil Kolom RecipeInstructions (Baris 1):\n", df_clean['RecipeInstructions'].iloc[0])
print("\nHasil Kolom Images (Baris 1):\n", df_clean['Images'].iloc[0])
if len(df_clean) > 1:
    print("Baris 2:", df_clean['Images'].iloc[1])

--- PEMBERSIHAN BERHASIL! ---

Hasil Kolom RecipeInstructions (Baris 1):
 1. Toss 2 cups berries with sugar.
2. Let stand for 45 minutes, stirring occasionally.
3. Transfer berry-sugar mixture to food processor.
4. Add yogurt and process until smooth.
5. Strain through fine sieve. Pour into baking pan (or transfer to ice cream maker and process according to manufacturers
6. ,
7. ,
8. ,
9. ,

Hasil Kolom Images (Baris 1):
 https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/YUeirxMLQaeE1h3v3qnM_229%20berry%20blue%20frzn%20dess.jpg
Baris 2: https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/39/picM9Mhnw.jpg

In [ ]:
df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"[blueberries, granulated sugar, vanilla yogurt...",1. Toss 2 cups berries with sugar.\n2. Let sta...,https://img.sndimg.com/food/image/upload/w_555...
1,39.0,Biryani,"[saffron, milk, hot green chili peppers, onion...",1. Soak saffron in warm milk for 5 minutes and...,https://img.sndimg.com/food/image/upload/w_555...
2,40.0,Best Lemonade,"[sugar, lemons, rind of, lemon, zest of, fresh...","1. Into a 1 quart Jar with tight fitting lid, ...",https://img.sndimg.com/food/image/upload/w_555...
3,41.0,Carina's Tofu-Vegetable Kebabs,"[extra firm tofu, eggplant, zucchini, mushroom...","1. Drain the tofu, carefully squeezing out exc...",https://img.sndimg.com/food/image/upload/w_555...
4,42.0,Cabbage Soup,"[plain tomato juice, cabbage, onion, carrots, ...",1. Mix everything together and bring to a boil...,https://img.sndimg.com/food/image/upload/w_555...

In [ ]:
# menyimpan dataset yang sudah siap dibersihkan

df_clean.to_csv("data_bersih_resep.csv", index=False)

# 2. Definisikan path folder dan nama file CSV Anda
folder_path = '/content/drive/MyDrive/Dataset/per tahap'
file_name = 'data_bersih_resep.csv'

# 3. Buat folder jika belum ada di Google Drive
os.makedirs(folder_path, exist_ok=True)

# 4. Gabungkan path folder dan nama file
full_path = os.path.join(folder_path, file_name)

# 5. Simpan DataFrame ke Google Drive
# Ganti 'nama_dataframe' dengan variabel DataFrame Anda di Colab
df_clean.to_csv(full_path, index=False)

print(f"File berhasil disimpan ke: {full_path}")

File berhasil disimpan ke: /content/drive/MyDrive/Dataset/per tahap/data_bersih_resep.csv

In [ ]:
df_clean.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images
0,38.0,Low-Fat Berry Blue Frozen Dessert,"[blueberries, granulated sugar, vanilla yogurt...",1. Toss 2 cups berries with sugar.\n2. Let sta...,https://img.sndimg.com/food/image/upload/w_555...
1,39.0,Biryani,"[saffron, milk, hot green chili peppers, onion...",1. Soak saffron in warm milk for 5 minutes and...,https://img.sndimg.com/food/image/upload/w_555...
2,40.0,Best Lemonade,"[sugar, lemons, rind of, lemon, zest of, fresh...","1. Into a 1 quart Jar with tight fitting lid, ...",https://img.sndimg.com/food/image/upload/w_555...
3,41.0,Carina's Tofu-Vegetable Kebabs,"[extra firm tofu, eggplant, zucchini, mushroom...","1. Drain the tofu, carefully squeezing out exc...",https://img.sndimg.com/food/image/upload/w_555...
4,42.0,Cabbage Soup,"[plain tomato juice, cabbage, onion, carrots, ...",1. Mix everything together and bring to a boil...,https://img.sndimg.com/food/image/upload/w_555...

# Model

In [ ]:
class RecipeRecommender:
    def __init__(self, df_recipes):
        self.df = df_recipes
        self.commodity_mapping = {
            'meat_beef': 'beef',
            'meat_chicken': 'chicken',
            'meat_chicken_broiler': 'chicken',
            'eggs': 'egg',
            'onions': 'onion',
            'chili': 'chili',
            'garlic': 'garlic',
            'oil': 'oil',
            'rice': 'rice',
            'sugar': 'sugar'
        }

    def _normalize_input(self, user_inputs):
        normalized = [self.commodity_mapping.get(item, item) for item in user_inputs]
        return set(normalized)

    def recommend(self, user_inputs):
        input_set = self._normalize_input(user_inputs)
        df_model = self.df.copy()

        # =========================================================================
        # PERBAIKAN: Ditambahkan 'if isinstance(x, list) else []'
        # Jika baris data berupa NaN (float), sistem otomatis mengabaikannya (dianggap list kosong)
        # =========================================================================

        # Tahap 1: Filtering (Mencari irisan)
        df_model['matched_ingredients'] = df_model['RecipeIngredientParts'].apply(
            lambda x: list(input_set.intersection(set(x))) if isinstance(x, list) else []
        )
        df_model['match_count'] = df_model['matched_ingredients'].apply(len)

        # Ambil yang minimal cocok 1 bahan
        candidates = df_model[df_model['match_count'] > 0].copy()

        # Tahap 2: Scoring (Menghitung bahan yang kurang)
        candidates['missing_count'] = candidates['RecipeIngredientParts'].apply(
            lambda x: len(set(x) - input_set) if isinstance(x, list) else 0
        )
        candidates['missing_ingredients'] = candidates['RecipeIngredientParts'].apply(
            lambda x: list(set(x) - input_set) if isinstance(x, list) else []
        )

        # Tahap 3: Ranking
        final_recommendations = candidates.sort_values(by=['match_count', 'missing_count'], ascending=[False, True])
        return final_recommendations

# ==========================================
# 2. SIMULASI DATA (Disesuaikan dengan selected_cols kamu)
# ==========================================
data_dummy = {
    'RecipeId': [1, 2, 3, 4, 5],
    'Name': ['Nasi Goreng Spesial', 'Telur Ceplok Bawang', 'Ayam Pedas Manis', 'Tumis Bawang Putih', 'Sup Ayam Bening'],
    'RecipeIngredientParts': [
        ['rice', 'egg', 'onion', 'garlic', 'chili', 'oil', 'salt'],
        ['egg', 'onion', 'garlic', 'oil'],
        ['chicken', 'chili', 'sugar', 'onion', 'oil'],
        ['garlic', 'oil', 'salt'],
        ['chicken', 'garlic', 'salt', 'water']
    ],
    'RecipeInstructions': ['Langkah 1...', 'Langkah 1...', 'Langkah 1...', 'Langkah 1...', 'Langkah 1...'],
    'Images': ['url1', 'url2', 'url3', 'url4', 'url5']
}
df_resep = pd.DataFrame(data_dummy)

# Inisialisasi Model untuk pengujian dummy
model = RecipeRecommender(df_resep)

# ==========================================
# 3. PENGUJIAN (TESTING SCENARIOS)
# ==========================================

def jalankan_tes(skenario_nama, input_user):
    print(f"--- MENGUJI: {skenario_nama} ---")
    print(f"Input User: {input_user}")

    hasil = model.recommend(input_user)

    if hasil.empty:
        print("-> Tidak ada resep ditemukan.\n")
        return

    for index, row in hasil.head(3).iterrows(): # Tampilkan top 3 saja
        print(f"Resep: {row['Name']}")
        print(f"   [+] Bahan Cocok ({row['match_count']}): {row['matched_ingredients']}")
        print(f"   [-] Kurang Bahan ({row['missing_count']}): {row['missing_ingredients']}\n")
    print("==========================================\n")

# Skenario 1: Input 1 Komoditi
jalankan_tes("Skenario 1 (Satu Bahan)", ['eggs'])

# Skenario 2: Input 2 Komoditi
jalankan_tes("Skenario 2 (Dua Bahan)", ['eggs', 'onions'])

# Skenario 3: Input 3 Komoditi
jalankan_tes("Skenario 3 (Tiga Bahan)", ['meat_chicken', 'chili', 'sugar'])

--- MENGUJI: Skenario 1 (Satu Bahan) ---
Input User: ['eggs']
Resep: Telur Ceplok Bawang
   [+] Bahan Cocok (1): ['egg']
   [-] Kurang Bahan (3): ['onion', 'oil', 'garlic']

Resep: Nasi Goreng Spesial
   [+] Bahan Cocok (1): ['egg']
   [-] Kurang Bahan (6): ['salt', 'garlic', 'oil', 'onion', 'chili', 'rice']

==========================================

--- MENGUJI: Skenario 2 (Dua Bahan) ---
Input User: ['eggs', 'onions']
Resep: Telur Ceplok Bawang
   [+] Bahan Cocok (2): ['onion', 'egg']
   [-] Kurang Bahan (2): ['oil', 'garlic']

Resep: Nasi Goreng Spesial
   [+] Bahan Cocok (2): ['onion', 'egg']
   [-] Kurang Bahan (5): ['salt', 'garlic', 'oil', 'chili', 'rice']

Resep: Ayam Pedas Manis
   [+] Bahan Cocok (1): ['onion']
   [-] Kurang Bahan (4): ['chicken', 'oil', 'sugar', 'chili']

==========================================

--- MENGUJI: Skenario 3 (Tiga Bahan) ---
Input User: ['meat_chicken', 'chili', 'sugar']
Resep: Ayam Pedas Manis
   [+] Bahan Cocok (3): ['chicken', 'sugar', 'chili']
   [-] Kurang Bahan (2): ['onion', 'oil']

Resep: Sup Ayam Bening
   [+] Bahan Cocok (1): ['chicken']
   [-] Kurang Bahan (3): ['salt', 'water', 'garlic']

Resep: Nasi Goreng Spesial
   [+] Bahan Cocok (1): ['chili']
   [-] Kurang Bahan (6): ['salt', 'garlic', 'oil', 'onion', 'egg', 'rice']

==========================================

In [ ]:
# 1. Inisialisasi model menggunakan data asli df_clean
model_asli = RecipeRecommender(df_clean)

# 2. Masukkan komoditi yang dicari
input_kamu = ['eggs', 'chili', 'onions']

# 3. Panggil fungsi rekomendasi (Sekarang sudah aman dari error float!)
df_hasil_rekomendasi = model_asli.recommend(input_kamu)

# 4. Tampilkan hasil 5 teratas
df_hasil_rekomendasi.head()

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions,Images,matched_ingredients,match_count,missing_count,missing_ingredients
311,376.0,Yellow Squash Puffs,"[egg, all-purpose flour, cornmeal, baking powd...","1. Combine the cooked squash and egg, stirring...",https://img.sndimg.com/food/image/upload/w_555...,"[onion, egg]",2,4,"[baking powder, cornmeal, salt, all-purpose fl..."
457,541.0,Slow-Cooker Grape Jelly Meatballs,"[lean beef, potato, egg, onion, heinz chili sa...",1. Sauce: 13 ounce bottle Heinz Chili Sauce 5 ...,,"[onion, egg]",2,4,"[potato, heinz chili sauce, lean beef, worcest..."
709,1008.0,Pizza Loaf,"[beef, onion, oregano, cheese spread, egg, but...",1. Brown the meat and onion.\n2. Season with o...,,"[onion, egg]",2,4,"[beef, cheese spread, oregano, butter]"
850,1526.0,Enchiladas Pollo With Green Chilies Cream Sauce,"[chicken breast half, onion, bay leaf, pepperc...",1. Place breasts in Dutch oven.\n2. Add water ...,,"[onion, egg]",2,6,"[monterey jack cheese, peppercorns, parmesan c..."
998,2100.0,Hush Puppies,"[flour, cornmeal, baking powder, salt, garlic ...","1. Stir together to mix thoroughly flour, corn...",,"[onion, egg]",2,6,"[baking powder, salt, buttermilk, cornmeal, ga..."

In [ ]:
# 1. Simpan DataFrame ke file CSV
df_clean.to_csv('resep_bersih.csv', index=False)

# 2. Download file CSV tersebut ke laptopmu
from google.colab import files
files.download('resep_bersih.csv')